// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalService.Infrastructure;

#nullable disable

namespace personalservice.Migrations
{
    [DbContext(typeof(PersonalDbContext))]
    [Migration("20260312154502_AddSolicitudesCambio")]
    partial class AddSolicitudesCambio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("PersonalService.Domain.Models.DocumentoPersonal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaEmision")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LegajoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LegajoId");

                    b.ToTable("Documentos", (string)null);
                });

            modelBuilder.Entity("PersonalService.Domain.Models.Domicilio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Depto")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LegajoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Piso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LegajoId");

                    b.ToTable("Domicilios", (string)null);
                });

            modelBuilder.Entity("PersonalService.Domain.Models.Familiar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ACargo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ACargoObraSocial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AplicaGanancias")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Discapacidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LegajoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Vive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LegajoId");

                    b.ToTable("Familiares");
                });

            modelBuilder.Entity("PersonalService.Domain.Models.Legajo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT");

                    b.Property<string>("Convenio")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObraSocial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sindicato")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPersonal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Legajos");
                });

            modelBuilder.Entity("PersonalService.Domain.Models.Licencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoSIJP")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConGoce")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CuentaVacaciones")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LegajoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LegajoId");

                    b.ToTable("Licencias");
                });

            modelBuilder.Entity("PersonalService.Domain.Models.SolicitudCambio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatosJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LegajoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("LegajoId");

                    b.ToTable("SolicitudesCambio", (string)null);
                });

            modelBuilder.Entity("PersonalService.Domain.Models.DocumentoPersonal", b =>
                {
                    b.HasOne("PersonalService.Domain.Models.Legajo", null)
                        .WithMany("Documentos")
                        .HasForeignKey("LegajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalService.Domain.Models.Domicilio", b =>
                {
                    b.HasOne("PersonalService.Domain.Models.Legajo", null)
                        .WithMany("Domicilios")
                        .HasForeignKey("LegajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalService.Domain.Models.Familiar", b =>
                {
                    b.HasOne("PersonalService.Domain.Models.Legajo", null)
                        .WithMany("Familiares")
                        .HasForeignKey("LegajoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PersonalService.Domain.Models.Licencia", b =>
                {
                    b.HasOne("PersonalService.Domain.Models.Legajo", null)
                        .WithMany("Licencias")
                        .HasForeignKey("LegajoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PersonalService.Domain.Models.SolicitudCambio", b =>
                {
                    b.HasOne("PersonalService.Domain.Models.Legajo", null)
                        .WithMany("Solicitudes")
                        .HasForeignKey("LegajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalService.Domain.Models.Legajo", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Domicilios");

                    b.Navigation("Familiares");

                    b.Navigation("Licencias");

                    b.Navigation("Solicitudes");
                });
#pragma warning restore 612, 618
        }
    }
}
