// <auto-generated />
using System;
using LiquidacionService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace liquidacionservice.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    [Migration("20260312113606_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("LiquidacionService.Domain.Models.PayrollRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Payrolls");
                });

            modelBuilder.Entity("LiquidacionService.Domain.Models.PayrollRun", b =>
                {
                    b.OwnsMany("LiquidacionService.Domain.Models.LegajoEnLote", "Legajos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Adicionales")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Antiguedad")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("AplicaGanancias")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Basico")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("BonosNoRemunerativos")
                                .HasColumnType("TEXT");

                            b1.Property<int>("CantHijos")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CantOtrosFamiliares")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Categoria")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Convenio")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("ConyugeACargo")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Cuil")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("DeduccionesAdicionales")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Descuentos")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("HorasExtra")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("NoRemunerativo")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("OmitirGanancias")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("PayrollRunId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Premios")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Presentismo")
                                .HasColumnType("TEXT");

                            b1.Property<int>("VacacionesDias")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("PayrollRunId");

                            b1.ToTable("LegajoEnLote");

                            b1.WithOwner()
                                .HasForeignKey("PayrollRunId");

                            b1.OwnsMany("LiquidacionService.Domain.Models.Embargo", "Embargos", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("TEXT");

                                    b2.Property<bool>("Activo")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("BaseCalculo")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("LegajoEnLoteId")
                                        .HasColumnType("TEXT");

                                    b2.Property<decimal?>("MontoFijo")
                                        .HasColumnType("TEXT");

                                    b2.Property<decimal?>("MontoPendiente")
                                        .HasColumnType("TEXT");

                                    b2.Property<decimal?>("MontoTotal")
                                        .HasColumnType("TEXT");

                                    b2.Property<decimal?>("Porcentaje")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Tipo")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("LegajoEnLoteId");

                                    b2.ToTable("Embargo");

                                    b2.WithOwner()
                                        .HasForeignKey("LegajoEnLoteId");
                                });

                            b1.OwnsMany("LiquidacionService.Domain.Models.LicenciaEnLote", "Licencias", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("TEXT");

                                    b2.Property<bool>("ConGoce")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Dias")
                                        .HasColumnType("INTEGER");

                                    b2.Property<Guid>("LegajoEnLoteId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Tipo")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("LegajoEnLoteId");

                                    b2.ToTable("LicenciaEnLote");

                                    b2.WithOwner()
                                        .HasForeignKey("LegajoEnLoteId");
                                });

                            b1.Navigation("Embargos");

                            b1.Navigation("Licencias");
                        });

                    b.OwnsMany("LiquidacionService.Domain.Models.PayrollReceipt", "Recibos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Deducciones")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("GeneradoEn")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("LegajoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("LegajoNombre")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("LegajoNumero")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Neto")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("PayrollRunId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Remunerativo")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("PayrollRunId");

                            b1.ToTable("PayrollReceipt");

                            b1.WithOwner()
                                .HasForeignKey("PayrollRunId");

                            b1.OwnsMany("LiquidacionService.Domain.Models.ReceiptDetail", "Detalle", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Concepto")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<decimal>("Importe")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("PayrollReceiptId")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("PayrollReceiptId");

                                    b2.ToTable("ReceiptDetail");

                                    b2.WithOwner()
                                        .HasForeignKey("PayrollReceiptId");
                                });

                            b1.Navigation("Detalle");
                        });

                    b.Navigation("Legajos");

                    b.Navigation("Recibos");
                });
#pragma warning restore 612, 618
        }
    }
}
