// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiemposService.Infrastructure;

#nullable disable

namespace tiemposservice.Migrations
{
    [DbContext(typeof(TiemposDbContext))]
    [Migration("20260313125017_AddAusencias")]
    partial class AddAusencias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("TiemposService.Domain.Models.Ausencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FechaDesde")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FechaHasta")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LegajoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegajoNumero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FechaDesde");

                    b.HasIndex("FechaHasta");

                    b.HasIndex("LegajoId");

                    b.HasIndex("LegajoNumero");

                    b.ToTable("Ausencias");
                });

            modelBuilder.Entity("TiemposService.Domain.Models.Fichada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LegajoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FechaHora");

                    b.HasIndex("LegajoId");

                    b.ToTable("Fichadas");
                });

            modelBuilder.Entity("TiemposService.Domain.Models.Horario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiasSemana")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TurnoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TurnoId");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("TiemposService.Domain.Models.PlanillaDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HorasAusencia")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HorasExtra")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HorasNormales")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LegajoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlanillaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LegajoId");

                    b.HasIndex("PlanillaId");

                    b.ToTable("PlanillaDetalles");
                });

            modelBuilder.Entity("TiemposService.Domain.Models.PlanillaHoras", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalHoras")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Periodo")
                        .IsUnique();

                    b.ToTable("Planillas");
                });

            modelBuilder.Entity("TiemposService.Domain.Models.Turno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ToleranciaMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("TiemposService.Domain.Models.PlanillaDetalle", b =>
                {
                    b.HasOne("TiemposService.Domain.Models.PlanillaHoras", null)
                        .WithMany("Detalles")
                        .HasForeignKey("PlanillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TiemposService.Domain.Models.PlanillaHoras", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
