// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NucleusWFService.Infrastructure;

#nullable disable

namespace nucleuswfservice.Migrations
{
    [DbContext(typeof(NucleusWfDbContext))]
    partial class NucleusWfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("NucleusWFService.Domain.Models.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoInicial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Definitions");
                });

            modelBuilder.Entity("NucleusWFService.Domain.Models.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Datos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Instances");
                });

            modelBuilder.Entity("NucleusWFService.Domain.Models.WorkflowDefinition", b =>
                {
                    b.OwnsMany("NucleusWFService.Domain.Models.WorkflowTransition", "Transiciones", b1 =>
                        {
                            b1.Property<Guid>("WorkflowDefinitionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("From")
                                .HasColumnType("TEXT");

                            b1.Property<string>("To")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Evento")
                                .HasColumnType("TEXT");

                            b1.HasKey("WorkflowDefinitionId", "From", "To", "Evento");

                            b1.ToTable("WorkflowTransition");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowDefinitionId");
                        });

                    b.Navigation("Transiciones");
                });

            modelBuilder.Entity("NucleusWFService.Domain.Models.WorkflowInstance", b =>
                {
                    b.OwnsMany("NucleusWFService.Domain.Models.WorkflowHistoryEntry", "Historial", b1 =>
                        {
                            b1.Property<Guid>("WorkflowInstanceId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset>("Timestamp")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Evento")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Actor")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("From")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("To")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("WorkflowInstanceId", "Timestamp", "Evento");

                            b1.ToTable("WorkflowHistoryEntry");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowInstanceId");
                        });

                    b.Navigation("Historial");
                });
#pragma warning restore 612, 618
        }
    }
}
